"""init

Revision ID: 1c3f6aed3db3
Revises: 
Create Date: 2025-05-05 20:12:16.469337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3f6aed3db3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('creator_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('captcha_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('answer', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_chat', 'captcha_answers', ['user_id', 'chat_id'], unique=False)
    op.create_index(op.f('ix_captcha_answers_chat_id'), 'captcha_answers', ['chat_id'], unique=False)
    op.create_index(op.f('ix_captcha_answers_expires_at'), 'captcha_answers', ['expires_at'], unique=False)
    op.create_index(op.f('ix_captcha_answers_user_id'), 'captcha_answers', ['user_id'], unique=False)
    op.create_table('captcha_message_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['groups.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_chat_msg', 'captcha_message_ids', ['user_id', 'chat_id'], unique=False)
    op.create_index(op.f('ix_captcha_message_ids_chat_id'), 'captcha_message_ids', ['chat_id'], unique=False)
    op.create_index(op.f('ix_captcha_message_ids_expires_at'), 'captcha_message_ids', ['expires_at'], unique=False)
    op.create_index(op.f('ix_captcha_message_ids_user_id'), 'captcha_message_ids', ['user_id'], unique=False)
    op.create_table('captcha_settings',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.chat_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captcha_settings')
    op.drop_index(op.f('ix_captcha_message_ids_user_id'), table_name='captcha_message_ids')
    op.drop_index(op.f('ix_captcha_message_ids_expires_at'), table_name='captcha_message_ids')
    op.drop_index(op.f('ix_captcha_message_ids_chat_id'), table_name='captcha_message_ids')
    op.drop_index('idx_user_chat_msg', table_name='captcha_message_ids')
    op.drop_table('captcha_message_ids')
    op.drop_index(op.f('ix_captcha_answers_user_id'), table_name='captcha_answers')
    op.drop_index(op.f('ix_captcha_answers_expires_at'), table_name='captcha_answers')
    op.drop_index(op.f('ix_captcha_answers_chat_id'), table_name='captcha_answers')
    op.drop_index('idx_user_chat', table_name='captcha_answers')
    op.drop_table('captcha_answers')
    op.drop_table('groups')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###