"""add mute_new_members to ChatSettings Table

Revision ID: 227ab193a8b6
Revises: e8de2e65711c
Create Date: 2025-05-13 23:59:42.101796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227ab193a8b6'
down_revision = 'e8de2e65711c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###