"""add created_at to captcha_settings

Revision ID: 7208a0d10485
Revises: e980b28d54b6
Create Date: 2025-05-05 21:05:27.172657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7208a0d10485'
down_revision = 'e980b28d54b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('captcha_settings', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('captcha_settings', 'created_at')
    # ### end Alembic commands ###