"""создал таблицу TimeoutMessageId

Revision ID: 8da9076c772d
Revises: 7208a0d10485
Create Date: 2025-05-05 21:50:22.382440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da9076c772d'
down_revision = '7208a0d10485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###