"""reated table roup

Revision ID: de327e90f316
Revises: 6058d484e73e
Create Date: 2025-04-24 02:36:48.986343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de327e90f316'
down_revision = '6058d484e73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###