"""groupuser table created for users

Revision ID: e8de2e65711c
Revises: 8da9076c772d
Create Date: 2025-05-06 09:51:50.908961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8de2e65711c'
down_revision = '8da9076c772d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###