"""add user_group table

Revision ID: e980b28d54b6
Revises: 1c3f6aed3db3
Create Date: 2025-05-05 20:41:11.469191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e980b28d54b6'
down_revision = '1c3f6aed3db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###